### ISSUE TITLE
Implement Room Stock Table Logic

### ISSUE THREAD

**Issue by JexonMG** [Dxbi11/Servibar#12]
### Description:

Implement a feature to manage Room Stock with the following requirements:

1. ### Select Options for Hotel and Floor:

Add two dropdown (select) options: one for selecting the Hotel and one for selecting the Floor.

2. ### Input for Room:

Add an input field to enter the Room number. This is necessary due to the large number of rooms.

3. ### Add Room Stock Table:

- Implement a button labeled "Add Room Stock Table".
- When clicked, the application should check if the room is available.
- If available, display the Room Stock table on the page.
- If not available, show a toast notification alerting the user.
- Table Management:
- Each Room Stock table should have a close button (an 'X' in the corner) to remove the table if it's no longer needed.
- Multiple Room Stock tables can be displayed simultaneously.

4. ### Remove All Tables Button:

- Add a red button near the select options and input field, labeled "Remove All Tables".
- When clicked, a popup should appear to confirm the action.
- If confirmed, all Room Stock tables should be removed from the page.

### Instructions:

- Add dropdowns for Hotel and Floor selection.
- Add an input field for entering the Room number.
- Implement the "Add Room Stock Table" button with the described functionality.
- Ensure each Room Stock table has a close button to remove individual tables.
- Add a "Remove All Tables" button with a confirmation popup to clear all tables.

### Acceptance Criteria:

- Dropdowns for Hotel and Floor are present and functional.
- Room number can be entered via an input field.
- "Add Room Stock Table" button checks room availability and displays the table or shows a toast notification accordingly.
- Each Room Stock table can be removed individually via a close button.
- "Remove All Tables" button successfully clears all tables after confirmation.

**Comment by Dxbi11** [comment]
Blud is taking too long 👎👎👎💯🤡


![3e93df19c2a27b3b1fe3d482d47e2940](https://github.com/Dxbi11/Servibar/assets/95590195/d12ed4be-d68c-4ecb-8eff-68b82b55f7ed)
