### ISSUE TITLE
Improve hotelRoomsTable component

### ISSUE THREAD

**Issue by Dxbi11** [Dxbi11/Servibar#5]
Currently the table is very convoluted, look into possible ways of dividing it into various smaller and potentially better components

**Comment by JexonMG** [comment]
Ya tardas bro, arregla eso master
🐒👌

**Comment by JexonMG** [comment]
![image](https://github.com/Dxbi11/Servibar/assets/143239658/7e38a080-a395-4f7e-8bf9-3b4847ccc8f6)

**Comment by JexonMG** [comment]
![image](https://github.com/Dxbi11/Servibar/assets/143239658/ae3d3ec5-46b9-4fd0-bf71-ce41e12ac505)

**Comment by Dxbi11** [comment]
iM TryINgg... 😭 😭 😢

**Comment by JexonMG** [comment]
Try better cuh😭🙏

**Comment by Dxbi11** [comment]
fuea carti 🧛 🧛‍♂️ 🔥
